"""initial

Revision ID: 6fc843bb7b0c
Revises: 
Create Date: 2026-01-26 10:24:49.515968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision: str = '6fc843bb7b0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE SEQUENCE IF NOT EXISTS u_id_seq START 1")
    op.create_table('address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capacities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capacity_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capacity_value')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('colors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('color_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('color_name')
    )
    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_chunks', 'document_embeddings', ['doc_id', 'chunk_index'], unique=False)
    op.create_index('idx_doc_type_title', 'document_embeddings', ['doc_type', 'title'], unique=False)
    op.create_index('idx_document_embedding_hnsw', 'document_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_document_type_id', 'document_embeddings', ['doc_type', 'doc_id'], unique=False)
    op.create_index('idx_metadata_gin', 'document_embeddings', ['meta_data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_embeddings_doc_id'), 'document_embeddings', ['doc_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_doc_type'), 'document_embeddings', ['doc_type'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_name')
    )
    op.create_table('fuels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuel_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_locations_coords', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', name='uq_permission_name_scope')
    )
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ACTIVE', 'INACTIVE', 'BOOKED', 'DELIVERED', 'RETURNING', 'RETURNED', 'COMPLETED', 'CANCELLED', 'REJECTED', 'PAID', 'REFUNDING', 'REFUNDED', 'CHARGED', 'INITIATED', 'SETTLED', 'READ', 'UNREAD', 'PENDING', 'RESPONDED', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('car_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('fuel_id', sa.Integer(), nullable=False),
    sa.Column('capacity_id', sa.Integer(), nullable=False),
    sa.Column('transmission_type', sa.Enum('MANUAL', 'AUTOMATIC', name='transmission_type_enum'), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('rental_per_hr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dynamic_rental_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kilometer_limit_per_hr', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capacity_id'], ['capacities.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_car_models_brand_model', 'car_models', ['brand', 'model'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.String(length=255), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_status_id'), 'users', ['status_id'], unique=False)
    op.create_table('admin_details',
    sa.Column('admin_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('admin_help_centre_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_help_centre_master_id'), 'admin_help_centre_master', ['id'], unique=False)
    op.create_table('car_model_features',
    sa.Column('car_model_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.PrimaryKeyConstraint('car_model_id', 'feature_id'),
    sa.UniqueConstraint('car_model_id', 'feature_id', name='uq_car_model_feature')
    )
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_no', sa.String(length=20), nullable=False),
    sa.Column('car_model_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('manufacture_year', sa.Integer(), nullable=False),
    sa.Column('image_urls', postgresql.ARRAY(sa.String(length=512)), nullable=False),
    sa.Column('last_serviced_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_frequency_months', sa.Integer(), nullable=False),
    sa.Column('insured_till', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pollution_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['car_models.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_model_id', 'color_id', name='uq_car_model_color'),
    sa.UniqueConstraint('car_no')
    )
    op.create_index('ix_cars_car_model_id', 'cars', ['car_model_id'], unique=False)
    op.create_index('ix_cars_status_id', 'cars', ['status_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=True)
    op.create_table('customer_details',
    sa.Column('customer_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('aadhaar_no', sa.String(length=12), nullable=True),
    sa.Column('license_no', sa.String(length=20), nullable=True),
    sa.Column('license_front_url', sa.String(length=512), nullable=True),
    sa.Column('aadhaar_front_url', sa.String(length=512), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('rookie_benefit_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('aadhaar_no'),
    sa.UniqueConstraint('address_id'),
    sa.UniqueConstraint('license_no'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_customer_details_tag_id'), 'customer_details', ['tag_id'], unique=False)
    op.create_table('faq_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_centre_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_help_centre_master_id'), 'help_centre_master', ['id'], unique=False)
    op.create_table('homepage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=True),
    sa.Column('hero_section', sa.JSON(), nullable=True),
    sa.Column('about_section', sa.JSON(), nullable=True),
    sa.Column('promotions_section', sa.JSON(), nullable=True),
    sa.Column('top_rental_section', sa.JSON(), nullable=True),
    sa.Column('explore_cars_section', sa.JSON(), nullable=True),
    sa.Column('reviews_section', sa.JSON(), nullable=True),
    sa.Column('contact_section', sa.JSON(), nullable=True),
    sa.Column('footer_section', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('receiver_id', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_urls', sa.JSON(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SUPPORT', 'PAYMENT', 'REFUND', 'SYSTEM', 'BOOKING', name='notification_type_enum'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_receiver_id'), 'notifications', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_index(op.f('ix_notifications_status_id'), 'notifications', ['status_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_table('privacy_policy_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queries_status_id'), 'queries', ['status_id'], unique=False)
    op.create_table('terms_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_by', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['last_modified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('recommended_car_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('based_on_bookings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_notified', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_recommendations_active', 'user_recommendations', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_recommendations_user_id'), 'user_recommendations', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('jti'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('admin_help_centre_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('admin_help_master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_help_master_id'], ['admin_help_centre_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_freezes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freeze_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delivery_longitude', sa.Float(), nullable=False),
    sa.Column('delivery_latitude', sa.Float(), nullable=False),
    sa.Column('pickup_longitude', sa.Float(), nullable=False),
    sa.Column('pickup_latitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_freezes_car_time', 'booking_freezes', ['car_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_booking_freezes_car_id'), 'booking_freezes', ['car_id'], unique=False)
    op.create_index(op.f('ix_booking_freezes_user_id'), 'booking_freezes', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=False),
    sa.Column('booking_status_id', sa.Integer(), nullable=False),
    sa.Column('payment_status_id', sa.Integer(), nullable=True),
    sa.Column('booked_by', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('payment_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_video_url', sa.String(length=512), nullable=True),
    sa.Column('delivery_otp', sa.String(length=6), nullable=True),
    sa.Column('delivery_otp_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('delivery_otp_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_kilometers', sa.Integer(), nullable=True),
    sa.Column('pickup_video_url', sa.String(length=512), nullable=True),
    sa.Column('pickup_otp', sa.String(length=6), nullable=True),
    sa.Column('pickup_otp_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('pickup_otp_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_kilometers', sa.Integer(), nullable=True),
    sa.Column('return_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.String(length=255), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=500), nullable=True),
    sa.Column('referral_benefit', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['booking_status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['delivery_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['payment_status_id'], ['status.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookings_dates', 'bookings', ['start_date', 'end_date'], unique=False)
    op.create_index('idx_bookings_status', 'bookings', ['booking_status_id', 'payment_status_id'], unique=False)
    op.create_index('idx_bookings_user', 'bookings', ['booked_by'], unique=False)
    op.create_index(op.f('ix_bookings_booking_status_id'), 'bookings', ['booking_status_id'], unique=False)
    op.create_index(op.f('ix_bookings_car_id'), 'bookings', ['car_id'], unique=False)
    op.create_index(op.f('ix_bookings_end_date'), 'bookings', ['end_date'], unique=False)
    op.create_index(op.f('ix_bookings_payment_status_id'), 'bookings', ['payment_status_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_date'), 'bookings', ['start_date'], unique=False)
    op.create_table('car_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_car_embedding_hnsw', 'car_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_car_embeddings_car_id'), 'car_embeddings', ['car_id'], unique=True)
    op.create_table('chat_threads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_session_id'), 'chat_threads', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_threads_thread_id'), 'chat_threads', ['thread_id'], unique=True)
    op.create_table('faq_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('faq_master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faq_master_id'], ['faq_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_centre_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('help_master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['help_master_id'], ['help_centre_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_car_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_range', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('homepage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homepage_id'], ['homepage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_contact_faqs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('homepage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homepage_id'], ['homepage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('discount', sa.String(length=10), nullable=False),
    sa.Column('timeline', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('PROMOTION', 'OFFER', name='promotion_type_enum'), nullable=False),
    sa.Column('homepage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homepage_id'], ['homepage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_top_rentals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homepage_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['homepage_id'], ['homepage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('privacy_policy_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('privacy_master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['privacy_master_id'], ['privacy_policy_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terms_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('terms_master_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['terms_master_id'], ['terms_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_help_centre_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('qa', sa.JSON(), nullable=True),
    sa.Column('table', sa.JSON(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['admin_help_centre_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('qa', sa.JSON(), nullable=True),
    sa.Column('table', sa.JSON(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['faq_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('help_centre_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('qa', sa.JSON(), nullable=True),
    sa.Column('table', sa.JSON(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['help_centre_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'NET_BANKING', name='payment_method_enum'), nullable=False),
    sa.Column('payment_type', sa.Enum('PAYMENT', 'ADD_PAYMENT', 'REFUND', 'CANCELLATION_REFUND', 'REJECTION_REFUND', name='payment_type_enum'), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=255), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=255), nullable=False),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=False),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id'),
    sa.UniqueConstraint('razorpay_payment_id'),
    sa.UniqueConstraint('razorpay_signature'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index('idx_payments_booking', 'payments', ['booking_id', 'status_id'], unique=False)
    op.create_index('idx_payments_transaction', 'payments', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_status_id'), 'payments', ['status_id'], unique=False)
    op.create_table('privacy_policy_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('qa', sa.JSON(), nullable=True),
    sa.Column('table', sa.JSON(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['privacy_policy_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_index(op.f('ix_reviews_car_id'), 'reviews', ['car_id'], unique=False)
    op.create_table('terms_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('qa', sa.JSON(), nullable=True),
    sa.Column('table', sa.JSON(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['terms_section.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_featured_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('homepage_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homepage_id'], ['homepage.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_featured_reviews')
    op.drop_table('terms_content')
    op.drop_index(op.f('ix_reviews_car_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_table('privacy_policy_content')
    op.drop_index(op.f('ix_payments_status_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_index('idx_payments_transaction', table_name='payments')
    op.drop_index('idx_payments_booking', table_name='payments')
    op.drop_table('payments')
    op.drop_table('help_centre_content')
    op.drop_table('faq_content')
    op.drop_table('admin_help_centre_content')
    op.drop_table('terms_section')
    op.drop_table('privacy_policy_section')
    op.drop_table('homepage_top_rentals')
    op.drop_table('homepage_promotions')
    op.drop_table('homepage_contact_faqs')
    op.drop_table('homepage_car_categories')
    op.drop_table('help_centre_section')
    op.drop_table('faq_section')
    op.drop_index(op.f('ix_chat_threads_thread_id'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_session_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_car_embeddings_car_id'), table_name='car_embeddings')
    op.drop_index('idx_car_embedding_hnsw', table_name='car_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('car_embeddings')
    op.drop_index(op.f('ix_bookings_start_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_status_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_date'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_car_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_status_id'), table_name='bookings')
    op.drop_index('idx_bookings_user', table_name='bookings')
    op.drop_index('idx_bookings_status', table_name='bookings')
    op.drop_index('idx_bookings_dates', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_booking_freezes_user_id'), table_name='booking_freezes')
    op.drop_index(op.f('ix_booking_freezes_car_id'), table_name='booking_freezes')
    op.drop_index('idx_freezes_car_time', table_name='booking_freezes')
    op.drop_table('booking_freezes')
    op.drop_table('admin_help_centre_section')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_recommendations_user_id'), table_name='user_recommendations')
    op.drop_index('idx_user_recommendations_active', table_name='user_recommendations')
    op.drop_table('user_recommendations')
    op.drop_table('terms_master')
    op.drop_index(op.f('ix_queries_status_id'), table_name='queries')
    op.drop_table('queries')
    op.drop_table('privacy_policy_master')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_receiver_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('homepage')
    op.drop_index(op.f('ix_help_centre_master_id'), table_name='help_centre_master')
    op.drop_table('help_centre_master')
    op.drop_table('faq_master')
    op.drop_index(op.f('ix_customer_details_tag_id'), table_name='customer_details')
    op.drop_table('customer_details')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index('ix_cars_status_id', table_name='cars')
    op.drop_index('ix_cars_car_model_id', table_name='cars')
    op.drop_table('cars')
    op.drop_table('car_model_features')
    op.drop_index(op.f('ix_admin_help_centre_master_id'), table_name='admin_help_centre_master')
    op.drop_table('admin_help_centre_master')
    op.drop_table('admin_details')
    op.drop_index(op.f('ix_users_status_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_car_models_brand_model', table_name='car_models')
    op.drop_table('car_models')
    op.drop_table('tags')
    op.drop_table('status')
    op.drop_table('roles')
    op.drop_table('revoked_tokens')
    op.drop_table('permissions')
    op.drop_index('idx_locations_coords', table_name='locations')
    op.drop_table('locations')
    op.drop_table('fuels')
    op.drop_table('features')
    op.drop_index(op.f('ix_document_embeddings_doc_type'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_doc_id'), table_name='document_embeddings')
    op.drop_index('idx_metadata_gin', table_name='document_embeddings', postgresql_using='gin')
    op.drop_index('idx_document_type_id', table_name='document_embeddings')
    op.drop_index('idx_document_embedding_hnsw', table_name='document_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_doc_type_title', table_name='document_embeddings')
    op.drop_index('idx_doc_chunks', table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.drop_table('colors')
    op.drop_table('categories')
    op.drop_table('capacities')
    op.drop_table('address')
    op.execute("DROP EXTENSION IF EXISTS vector")
    op.execute("DROP SEQUENCE IF EXISTS u_id_seq")
    # ### end Alembic commands ###
