from decimal import Decimal

from app.models.enums import Tags, TransmissionType, StatusEnum


CAR_MODELS_DATA = [
    {
        "brand": "Toyota",
        "model": "Fortuner",
        "category": "SUV",
        "fuel": "Diesel",
        "capacity": 7,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 12,
        "rental_per_hr": Decimal("300.50"),
        "dynamic_rental_price": Decimal("300.50"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Sunroof",
            "360 Camera",
            "Airbags",
            "Bluetooth Audio",
            "Leather Seats",
            "Air Conditioning",
        ],
    },
    {
        "brand": "Honda",
        "model": "City",
        "category": "Sedan",
        "fuel": "Petrol",
        "capacity": 5,
        "transmission_type": TransmissionType.MANUAL,
        "mileage": 18,
        "rental_per_hr": Decimal("200.00"),
        "dynamic_rental_price": Decimal("200.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Bluetooth Audio",
            "Air Conditioning",
            "Power Steering",
            "Touchscreen",
        ],
    },
    {
        "brand": "Maruti",
        "model": "Swift",
        "category": "Hatchback",
        "fuel": "Petrol",
        "capacity": 5,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 22,
        "rental_per_hr": Decimal("150.00"),
        "dynamic_rental_price": Decimal("150.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Touchscreen",
            "Air Conditioning",
            "Power Steering",
            "Rear Camera",
        ],
    },
    {
        "brand": "Tata",
        "model": "Nexon EV",
        "category": "SUV",
        "fuel": "Electric",
        "capacity": 5,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 0,
        "rental_per_hr": Decimal("250.00"),
        "dynamic_rental_price": Decimal("250.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Sunroof",
            "Airbags",
            "Fast Charging",
            "Touchscreen",
            "GPS Navigation",
        ],
    },
    {
        "brand": "Kia",
        "model": "Seltos",
        "category": "SUV",
        "fuel": "Diesel",
        "capacity": 5,
        "transmission_type": TransmissionType.MANUAL,
        "mileage": 16,
        "rental_per_hr": Decimal("275.00"),
        "dynamic_rental_price": Decimal("275.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Sunroof",
            "Bose Speakers",
            "GPS Navigation",
            "360 Camera",
        ],
    },
    {
        "brand": "Hyundai",
        "model": "i20",
        "category": "Hatchback",
        "fuel": "Petrol",
        "capacity": 5,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 20,
        "rental_per_hr": Decimal("180.00"),
        "dynamic_rental_price": Decimal("180.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Touchscreen",
            "Air Conditioning",
            "Keyless Entry",
            "Parking Sensors",
        ],
    },
    {
        "brand": "Mahindra",
        "model": "Scorpio",
        "category": "SUV",
        "fuel": "Diesel",
        "capacity": 7,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 14,
        "rental_per_hr": Decimal("350.00"),
        "dynamic_rental_price": Decimal("350.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Sunroof",
            "Airbags",
            "Leather Seats",
            "Touchscreen",
            "Cruise Control",
        ],
    },
    {
        "brand": "Volkswagen",
        "model": "Polo",
        "category": "Hatchback",
        "fuel": "Petrol",
        "capacity": 5,
        "transmission_type": TransmissionType.MANUAL,
        "mileage": 18,
        "rental_per_hr": Decimal("170.00"),
        "dynamic_rental_price": Decimal("170.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Touchscreen",
            "Air Conditioning",
            "Power Steering",
            "Central Locking",
        ],
    },
    {
        "brand": "Ford",
        "model": "EcoSport",
        "category": "SUV",
        "fuel": "Diesel",
        "capacity": 5,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 15,
        "rental_per_hr": Decimal("220.00"),
        "dynamic_rental_price": Decimal("220.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Touchscreen",
            "Rear Camera",
            "Air Conditioning",
            "Fog Lamps",
        ],
    },
    {
        "brand": "Renault",
        "model": "Duster",
        "category": "SUV",
        "fuel": "Petrol",
        "capacity": 5,
        "transmission_type": TransmissionType.MANUAL,
        "mileage": 13,
        "rental_per_hr": Decimal("240.00"),
        "dynamic_rental_price": Decimal("240.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Hill Assist",
            "Bluetooth Audio",
            "Air Conditioning",
            "Roof Rails",
        ],
    },
    {
        "brand": "Nissan",
        "model": "Magnite",
        "category": "SUV",
        "fuel": "Petrol",
        "capacity": 5,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 17,
        "rental_per_hr": Decimal("190.00"),
        "dynamic_rental_price": Decimal("190.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Airbags",
            "Touchscreen",
            "360 Camera",
            "Air Conditioning",
            "Keyless Entry",
        ],
    },
    {
        "brand": "MG",
        "model": "Hector",
        "category": "SUV",
        "fuel": "Petrol",
        "capacity": 7,
        "transmission_type": TransmissionType.AUTOMATIC,
        "mileage": 14,
        "rental_per_hr": Decimal("320.00"),
        "dynamic_rental_price": Decimal("320.00"),
        "kilometer_limit_per_hr": 50,
        "features": [
            "Sunroof",
            "Airbags",
            "Panoramic Sunroof",
            "GPS Navigation",
            "Voice Commands",
            "Touchscreen",
        ],
    },
]

CARS_DATA = [
    # Toyota Fortuner - 3 cars with different colors
    {
        "car_no": "MH12AB1234",
        "car_model": {"brand": "Toyota", "model": "Fortuner"},
        "color": "White",
        "manufacture_year": 2022,
        "image_urls": [
            "assets/images/cars/toyotafortuner_white.png",
            "assets/images/cars/toyotafortuner_white.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-15T00:00:00",
        "insured_till": "2025-01-14T00:00:00",
        "pollution_expiry": "2025-01-14T00:00:00",
    },
    {
        "car_no": "MH12AB1235",
        "car_model": {"brand": "Toyota", "model": "Fortuner"},
        "color": "Black",
        "manufacture_year": 2022,
        "image_urls": [
            "assets/images/cars/toyotafortuner_black.png",
            "assets/images/cars/toyotafortuner_black.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-02-10T00:00:00",
        "insured_till": "2025-02-09T00:00:00",
        "pollution_expiry": "2025-02-09T00:00:00",
    },
    {
        "car_no": "MH12AB1236",
        "car_model": {"brand": "Toyota", "model": "Fortuner"},
        "color": "Silver",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/toyotafortuner_silver.png",
            "assets/images/cars/toyotafortuner_silver.png",
        ],
        "status": StatusEnum.INACTIVE,
        "last_serviced_date": "2024-03-05T00:00:00",
        "insured_till": "2025-03-04T00:00:00",
        "pollution_expiry": "2025-03-04T00:00:00",
    },
    # Honda City - 2 cars with different colors
    {
        "car_no": "KA03CD5678",
        "car_model": {"brand": "Honda", "model": "City"},
        "color": "Silver",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/hondacity_silver.png",
            "assets/images/cars/hondacity_silver.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-02-20T00:00:00",
        "insured_till": "2025-02-19T00:00:00",
        "pollution_expiry": "2025-02-19T00:00:00",
    },
    {
        "car_no": "KA03CD5679",
        "car_model": {"brand": "Honda", "model": "City"},
        "color": "Red",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/hondacity_red.png",
            "assets/images/cars/hondacity_red.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-25T00:00:00",
        "insured_till": "2025-01-24T00:00:00",
        "pollution_expiry": "2025-01-24T00:00:00",
    },
    # Maruti Swift - 2 cars with different colors
    {
        "car_no": "DL05EF9012",
        "car_model": {"brand": "Maruti", "model": "Swift"},
        "color": "Red",
        "manufacture_year": 2024,
        "image_urls": [
            "assets/images/cars/marutiswift_red.png",
            "assets/images/cars/marutiswift_red.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-03-10T00:00:00",
        "insured_till": "2025-03-09T00:00:00",
        "pollution_expiry": "2025-03-09T00:00:00",
    },
    {
        "car_no": "DL05EF9013",
        "car_model": {"brand": "Maruti", "model": "Swift"},
        "color": "Blue",
        "manufacture_year": 2024,
        "image_urls": [
            "assets/images/cars/marutiswift_blue.png",
            "assets/images/cars/marutiswift_blue.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-02-28T00:00:00",
        "insured_till": "2025-02-27T00:00:00",
        "pollution_expiry": "2025-02-27T00:00:00",
    },
    # Tata Nexon EV - 2 cars with different colors
    {
        "car_no": "TN07GH3456",
        "car_model": {"brand": "Tata", "model": "Nexon EV"},
        "color": "Blue",
        "manufacture_year": 2024,
        "image_urls": [
            "assets/images/cars/tatanexonev_blue.png",
            "assets/images/cars/tatanexonev_blue.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-20T00:00:00",
        "insured_till": "2025-01-19T00:00:00",
        "pollution_expiry": "2025-01-19T00:00:00",
    },
    {
        "car_no": "TN07GH3457",
        "car_model": {"brand": "Tata", "model": "Nexon EV"},
        "color": "White",
        "manufacture_year": 2024,
        "image_urls": [
            "assets/images/cars/tatanexonev_white.png",
            "assets/images/cars/tatanexonev_white.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-02-15T00:00:00",
        "insured_till": "2025-02-14T00:00:00",
        "pollution_expiry": "2025-02-14T00:00:00",
    },
    # Kia Seltos - 2 cars with different colors
    {
        "car_no": "PB09IJ7890",
        "car_model": {"brand": "Kia", "model": "Seltos"},
        "color": "Black",
        "manufacture_year": 2021,
        "image_urls": [
            "assets/images/cars/kiaseltos_black.png",
            "assets/images/cars/kiaseltos_black.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-10T00:00:00",
        "insured_till": "2024-12-31T00:00:00",
        "pollution_expiry": "2024-12-31T00:00:00",
    },
    {
        "car_no": "PB09IJ7891",
        "car_model": {"brand": "Kia", "model": "Seltos"},
        "color": "Gray",
        "manufacture_year": 2022,
        "image_urls": [
            "assets/images/cars/kiaseltos_gray.png",
            "assets/images/cars/kiaseltos_gray.png",
        ],
        "status": StatusEnum.INACTIVE,
        "last_serviced_date": "2024-03-01T00:00:00",
        "insured_till": "2025-02-28T00:00:00",
        "pollution_expiry": "2025-02-28T00:00:00",
    },
    # Hyundai i20
    {
        "car_no": "MH01KL2345",
        "car_model": {"brand": "Hyundai", "model": "i20"},
        "color": "White",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/hyundaii20_white.png",
            "assets/images/cars/hyundaii20_white.png",
        ],
        "status": StatusEnum.INACTIVE,
        "last_serviced_date": "2024-02-05T00:00:00",
        "insured_till": "2025-02-04T00:00:00",
        "pollution_expiry": "2025-02-04T00:00:00",
    },
    # Mahindra Scorpio
    {
        "car_no": "KA04MN6789",
        "car_model": {"brand": "Mahindra", "model": "Scorpio"},
        "color": "Black",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/mahindrascorpio_black.png",
            "assets/images/cars/mahindrascorpio_black.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-30T00:00:00",
        "insured_till": "2025-01-29T00:00:00",
        "pollution_expiry": "2025-01-29T00:00:00",
    },
    {
        "car_no": "KA04MN6790",
        "car_model": {"brand": "Mahindra", "model": "Scorpio"},
        "color": "White",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/mahindrascorpio_white.png",
            "assets/images/cars/mahindrascorpio_white.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-30T00:00:00",
        "insured_till": "2025-01-29T00:00:00",
        "pollution_expiry": "2025-01-29T00:00:00",
    },
    # Volkswagen Polo
    {
        "car_no": "DL08OP4567",
        "car_model": {"brand": "Volkswagen", "model": "Polo"},
        "color": "Red",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/volkswagenpolo_red.png",
            "assets/images/cars/volkswagenpolo_red.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-02-10T00:00:00",
        "insured_till": "2025-02-09T00:00:00",
        "pollution_expiry": "2025-02-09T00:00:00",
    },
    # Ford EcoSport
    {
        "car_no": "MH14QR8901",
        "car_model": {"brand": "Ford", "model": "EcoSport"},
        "color": "White",
        "manufacture_year": 2022,
        "image_urls": [
            "assets/images/cars/fordecosport_white.png",
            "assets/images/cars/fordecosport_white.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-18T00:00:00",
        "insured_till": "2025-01-17T00:00:00",
        "pollution_expiry": "2025-01-17T00:00:00",
    },
    {
        "car_no": "MH14QR8902",
        "car_model": {"brand": "Ford", "model": "EcoSport"},
        "color": "Black",
        "manufacture_year": 2022,
        "image_urls": [
            "assets/images/cars/fordecosport_black.png",
            "assets/images/cars/fordecosport_black.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-18T00:00:00",
        "insured_till": "2025-01-17T00:00:00",
        "pollution_expiry": "2025-01-17T00:00:00",
    },
    # Renault Duster
    {
        "car_no": "RJ06ST2345",
        "car_model": {"brand": "Renault", "model": "Duster"},
        "color": "Gray",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/renaultduster_gray.png",
            "assets/images/cars/renaultduster_gray.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-03-02T00:00:00",
        "insured_till": "2025-03-01T00:00:00",
        "pollution_expiry": "2025-03-01T00:00:00",
    },
    # Nissan Magnite
    {
        "car_no": "TN09UV6789",
        "car_model": {"brand": "Nissan", "model": "Magnite"},
        "color": "Blue",
        "manufacture_year": 2024,
        "image_urls": [
            "assets/images/cars/nissanmagnite_blue.png",
            "assets/images/cars/nissanmagnite_blue.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-02-25T00:00:00",
        "insured_till": "2025-02-24T00:00:00",
        "pollution_expiry": "2025-02-24T00:00:00",
    },
    # MG Hector
    {
        "car_no": "KA05WX1234",
        "car_model": {"brand": "MG", "model": "Hector"},
        "color": "Silver",
        "manufacture_year": 2023,
        "image_urls": [
            "assets/images/cars/mghector_silver.png",
            "assets/images/cars/mghector_silver.png",
        ],
        "status": StatusEnum.ACTIVE,
        "last_serviced_date": "2024-01-22T00:00:00",
        "insured_till": "2025-01-21T00:00:00",
        "pollution_expiry": "2025-01-21T00:00:00",
    },
]

__all__ = ["CAR_MODELS_DATA", "CARS_DATA"]