TERMS_DATA = {
    "is_active": True,
    "sections": [
        {
            "title": "1. Introduction & Acceptance of Terms",
            "order": 1,
            "contents": [
                {
                    "type": "text",
                    "text": "This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "This document sets out the Terms and Conditions for renting vehicles from M/s Cruizo Motor Company Pvt. Ltd. (hereinafter referred to as 'Cruizo') and Users (hereinafter referred to as 'User'). This document is legally binding between the User and Cruizo. This document will be effective upon your acceptance of the same and will govern the relationship between User and Cruizo for the use of the vehicles offered through the website and mobile application.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "Users are requested to read the Terms and Conditions carefully before booking. By accessing the platform or booking a vehicle, you agree to be bound by these terms. If you do not agree, please do not use the services.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "2. Eligibility & Document Verification",
            "order": 2,
            "contents": [
                {
                    "type": "text",
                    "text": "To rent a vehicle from Cruizo, the User must meet the following eligibility criteria:",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "i. Age: The User must be at least 18 years of age.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "ii. Driving License: The User must hold a valid, original Driving License (LMV Non-Transport) recognized by the Government of India.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iii. Identity Proof: The User must possess a valid Aadhaar Card.",
                    "order": 4,
                },
                {
                    "type": "text",
                    "text": "iv. Document Upload & Verification: It is mandatory for the User to upload clear images of their Driving License and Aadhaar Card, along with the respective document numbers, to the Customer Profile page. Cruizo reserves the right to verify these documents. If the documents are found to be invalid, forged, expired, or unclear, Cruizo reserves the right to reject the booking.",
                    "order": 5,
                },
            ],
        },
        {
            "title": "3. Booking, Pricing & Security Deposit",
            "order": 3,
            "contents": [
                {
                    "type": "text",
                    "text": "The total payable amount for any booking is calculated based on the following components:",
                    "order": 1,
                },
                {
                    "type": "table",
                    "table": {
                        "columns": ["Component", "Calculation Method"],
                        "rows": [
                            [
                                "Rental Base Amount",
                                "Duration (Hours) × Car Model's Dynamic Rental Price",
                            ],
                            [
                                "Security Deposit",
                                "10 × Car Model's Dynamic Rental Price",
                            ],
                        ],
                    },
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "The Security Deposit is refundable subject to the successful completion of the trip without any damages, violations, or late returns. The refund will be processed within 7 days of trip completion.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "4. Cancellation, Rejection & Refund Policy",
            "order": 4,
            "contents": [
                {
                    "type": "text",
                    "text": "Cruizo operates on a strict inventory reservation model. Once a car is booked, it is removed from availability for other users. Consequently, refunds are processed based on the following matrix:",
                    "order": 1,
                },
                {
                    "type": "table",
                    "table": {
                        "columns": [
                            "Scenario",
                            "Condition",
                            "Base Rental Refund",
                            "Security Deposit Refund",
                        ],
                        "rows": [
                            [
                                "Customer Cancellation",
                                "More than 2 hours before Start Time",
                                "50% Refund",
                                "100% Refund",
                            ],
                            [
                                "Customer Cancellation",
                                "Less than 2 hours before Start Time",
                                "0% Refund (No Refund)",
                                "100% Refund",
                            ],
                            [
                                "Admin Rejection",
                                "Due to invalid documents, fraud, or non-compliance",
                                "0% Refund (Forfeited)",
                                "100% Refund",
                            ],
                        ],
                    },
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "IMPORTANT NOTE ON ADMIN REJECTION: If a booking is rejected by the Cruizo Admin due to the User's failure to provide valid documents (e.g., invalid license, blurred images, expired ID), the Base Rental Amount will be forfeited and NOT refunded. This is because the vehicle slot was reserved for the User, preventing other customers from booking it during that time.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "5. Vehicle Usage, Mileage & Prohibited Acts",
            "order": 5,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Mileage Limit: All bookings come with a pre-defined mileage limit. Any usage exceeding this limit will incur additional charges per kilometer, which will be deducted from the Security Deposit.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Prohibited Acts: The vehicle shall not be used for: (a) transporting prohibited/illegal goods; (b) racing, rallying, or stunts; (c) towing other vehicles; (d) driving under the influence of alcohol or drugs. Violation of this clause will result in immediate termination of booking, forfeiture of security deposit, and legal action.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Geographic Limit: Vehicles must not be taken outside the permitted geographical boundaries without prior written consent from Cruizo.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "6. Late Returns & Overtime Charges",
            "order": 6,
            "contents": [
                {
                    "type": "text",
                    "text": "Users are expected to return the vehicle by the agreed booking end time. The following penalty structure applies for delays:",
                    "order": 1,
                },
                {
                    "type": "table",
                    "table": {
                        "columns": ["Delay Duration", "Penalty / Charge"],
                        "rows": [
                            [
                                "Grace Period",
                                "Up to 30 minutes from booking end time (No Charge)",
                            ],
                            [
                                "Late Return (> 30 mins)",
                                "Charged at 1.5x (150%) of the Hourly Rental Rate for the extended duration",
                            ],
                        ],
                    },
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "Cruizo reserves the right to deduct these late charges directly from the Security Deposit. If the penalty exceeds the deposit, the User agrees to pay the balance immediately.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "7. Damages, Accidents & Traffic Violations",
            "order": 7,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Damages: The User is solely responsible for any physical damage, scratches, dents, or mechanical failure resulting from negligent driving. The cost of repairs will be recovered from the Security Deposit. If repair costs exceed the deposit, the User is liable to pay the difference.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Traffic Violations: The User is 100% responsible for any traffic fines, challans, or penalties incurred during the rental period. If Cruizo receives a notice for a violation committed during the User's booking, the fine amount plus a processing fee will be charged to the User.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Accidents: In the event of an accident, the User must immediately inform Cruizo Support and the police (if necessary). The User must not leave the scene or admit liability without consulting Cruizo.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "8. Car Availability & Color",
            "order": 8,
            "contents": [
                {
                    "type": "text",
                    "text": "Cruizo guarantees the vehicle model (e.g., Swift, Thar) booked by the User. However, the specific color of the vehicle is subject to availability at the time of pickup. Requests for specific colors are not guaranteed.",
                    "order": 1,
                }
            ],
        },
        {
            "title": "9. Indemnity & Governing Law",
            "order": 9,
            "contents": [
                {
                    "type": "text",
                    "text": "The User agrees to indemnify and hold harmless Cruizo, its directors, employees, and agents from any claims, losses, damages, or expenses arising out of the User's breach of these Terms, violation of laws, or negligent use of the vehicle.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "These Terms shall be governed by the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in the city where the vehicle was rented.",
                    "order": 2,
                },
            ],
        },
        {
            "title": "10. Insurance Coverage & Liability",
            "order": 10,
            "contents": [
                {
                    "type": "text",
                    "text": "All vehicles provided by Cruizo are covered by comprehensive insurance as per Indian Motor Vehicles Act. However, the User must note the following:",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "i. Insurance Deductible: In case of an accident or damage, the User may be liable for the insurance deductible amount, which will be deducted from the Security Deposit.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "ii. Personal Accident Cover: The insurance covers third-party liability and vehicle damage. Personal accident insurance for the driver and passengers is the User's responsibility.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iii. Exclusions: The insurance does not cover damages resulting from drunk driving, racing, off-road use, or violation of traffic laws. In such cases, the User bears full liability for all damages and legal consequences.",
                    "order": 4,
                },
                {
                    "type": "text",
                    "text": "iv. Theft or Total Loss: In the event of vehicle theft or total loss due to User negligence, the User may be held liable for the full market value of the vehicle after insurance claim settlement.",
                    "order": 5,
                },
            ],
        },
        {
            "title": "11. Fuel Policy & Vehicle Condition",
            "order": 11,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Fuel at Pickup: Vehicles are provided with a specified fuel level at the time of pickup. The User must note this level in the delivery checklist.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Fuel at Return: The User must return the vehicle with the same fuel level as at pickup. If the fuel level is lower, Cruizo reserves the right to charge the User for the fuel difference plus a service fee of ₹200.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Pre-Delivery Inspection: Users are required to inspect the vehicle thoroughly at the time of delivery and report any pre-existing damages, scratches, or issues. Failure to report will result in the User being held responsible for such damages at the time of return.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. Cleanliness: The vehicle must be returned in a reasonably clean condition. Excessive dirt, stains, or foul odor may result in a cleaning charge of up to ₹1,500 being deducted from the Security Deposit.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "12. Breakdown & Roadside Assistance",
            "order": 12,
            "contents": [
                {
                    "type": "text",
                    "text": "i. 24/7 Support: Cruizo provides 24/7 roadside assistance for mechanical breakdowns, flat tires, battery issues, and other vehicle-related emergencies during the rental period.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. User Responsibility: The User must immediately contact Cruizo Support in case of any breakdown or mechanical issue. The User must not attempt unauthorized repairs or modifications to the vehicle.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Replacement Vehicle: In case of a breakdown due to mechanical failure (not caused by User negligence), Cruizo will make reasonable efforts to provide a replacement vehicle of similar category, subject to availability.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. Towing Charges: If the vehicle requires towing due to User negligence (e.g., running out of fuel, driving in prohibited areas), the towing charges will be borne by the User.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "13. Extension & Modification of Booking",
            "order": 13,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Extension Requests: Users may request to extend their booking period through the mobile app or by contacting Cruizo Support. Extensions are subject to vehicle availability and must be requested at least 2 hours before the original booking end time.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Extension Charges: If approved, the extension will be charged at the prevailing hourly rate for the vehicle. The User must pay the extension charges before the extension is confirmed.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Modification Restrictions: Changes to pickup location, vehicle model, or booking dates may not be possible after booking confirmation. Users are advised to cancel and rebook if major changes are required.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. No-Show Policy: If the User fails to pick up the vehicle within 2 hours of the scheduled pickup time without prior notification, the booking will be automatically cancelled with zero refund on the Base Rental Amount.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "14. Data Privacy & GPS Tracking",
            "order": 14,
            "contents": [
                {
                    "type": "text",
                    "text": "i. GPS Monitoring: All vehicles are equipped with GPS tracking devices for security and fleet management purposes. By renting a vehicle, the User consents to GPS tracking during the rental period.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Data Usage: GPS data is used solely for vehicle recovery in case of theft, route verification for mileage calculation, and ensuring the vehicle is not taken outside permitted geographical boundaries.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Privacy Compliance: Cruizo is committed to protecting User privacy. All personal data collected is handled in accordance with our Privacy Policy and applicable data protection laws.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. Tampering Prohibited: Any attempt to disable, remove, or tamper with the GPS device will result in immediate termination of the booking, forfeiture of the Security Deposit, and legal action.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "15. Smoking, Pets & Prohibited Items",
            "order": 15,
            "contents": [
                {
                    "type": "text",
                    "text": "i. No Smoking: Smoking (including e-cigarettes and vaping) is strictly prohibited inside all Cruizo vehicles. Violation will result in a deep-cleaning charge of ₹3,000 being deducted from the Security Deposit.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Pets: Pets are not allowed in the vehicles unless prior written permission is obtained from Cruizo. Unauthorized transportation of pets may result in a cleaning and sanitization charge of ₹2,500.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Prohibited Items: The vehicle must not be used to transport illegal substances, hazardous materials, explosives, or any items prohibited under Indian law. Violation will result in immediate police notification and legal action.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. Commercial Use: The vehicle is rented for personal use only. Commercial use (e.g., ride-sharing, delivery services, taxi operations) is strictly prohibited without a separate commercial rental agreement.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "16. Force Majeure",
            "order": 16,
            "contents": [
                {
                    "type": "text",
                    "text": "Cruizo shall not be liable for any failure or delay in performing its obligations under these Terms if such failure or delay is due to circumstances beyond its reasonable control, including but not limited to:",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "i. Acts of God (earthquakes, floods, storms, pandemics)",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "ii. Government actions, civil unrest, or war",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iii. Strikes, lockouts, or labor disputes",
                    "order": 4,
                },
                {
                    "type": "text",
                    "text": "iv. Failure of public utilities or transportation systems",
                    "order": 5,
                },
                {
                    "type": "text",
                    "text": "In such events, Cruizo will make reasonable efforts to notify affected Users and provide alternative solutions or refunds as appropriate.",
                    "order": 6,
                },
            ],
        },
        {
            "title": "17. Dispute Resolution & Arbitration",
            "order": 17,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Amicable Resolution: In the event of any dispute arising out of or relating to these Terms, both parties agree to first attempt to resolve the matter through good-faith negotiations.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Arbitration: If the dispute cannot be resolved amicably within 30 days, it shall be referred to arbitration in accordance with the Arbitration and Conciliation Act, 1996. The arbitration shall be conducted by a sole arbitrator mutually appointed by both parties.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Venue: The seat of arbitration shall be the city where the vehicle was rented, and the proceedings shall be conducted in English.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. Costs: Each party shall bear its own costs of arbitration unless the arbitrator determines otherwise based on the outcome.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "18. Modification of Terms",
            "order": 18,
            "contents": [
                {
                    "type": "text",
                    "text": "Cruizo reserves the right to modify, amend, or update these Terms and Conditions at any time without prior notice. The updated Terms will be effective immediately upon posting on the website and mobile application.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "Users are advised to review the Terms periodically. Continued use of Cruizo services after any modifications constitutes acceptance of the revised Terms.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "For bookings made before a Terms update, the version of the Terms in effect at the time of booking shall apply to that specific booking.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "19. Contact Information & Customer Support",
            "order": 19,
            "contents": [
                {
                    "type": "text",
                    "text": "For any queries, complaints, or assistance regarding these Terms or your booking, please contact Cruizo through the following channels:",
                    "order": 1,
                },
                {
                    "type": "table",
                    "table": {
                        "columns": ["Contact Type", "Details"],
                        "rows": [
                            [
                                "Email Support",
                                "support@cruizo.in (Response within 24 hours)",
                            ],
                            [
                                "Emergency Helpline",
                                "+91-1234567890 (24/7 for on-trip issues)",
                            ],
                            [
                                "Registered Office",
                                "Cruizo Car Rental Pvt. Ltd., 123, High Street, Workafella, Teynampet, Chennai - 600018, Tamil Nadu, India",
                            ],
                            [
                                "Customer Support Hours",
                                "Monday to Sunday: 9:00 AM - 9:00 PM IST",
                            ],
                        ],
                    },
                    "order": 2,
                },
            ],
        },
        {
            "title": "20. Severability & Entire Agreement",
            "order": 20,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Severability: If any provision of these Terms is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, such provision shall be severed from these Terms, and the remaining provisions shall continue in full force and effect.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Entire Agreement: These Terms, together with the Privacy Policy and any other policies referenced herein, constitute the entire agreement between the User and Cruizo regarding the rental of vehicles and supersede all prior agreements, understandings, or representations.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Waiver: No waiver of any term or condition of these Terms shall be deemed a further or continuing waiver of such term or any other term. Cruizo's failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iv. Assignment: The User may not assign or transfer these Terms or any rights hereunder without Cruizo's prior written consent. Cruizo may assign these Terms without restriction.",
                    "order": 4,
                },
                {
                    "type": "text",
                    "text": "By proceeding with a booking, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions. Thank you for choosing Cruizo!",
                    "order": 5,
                },
            ],
        },
    ],
}

HELPCENTRE_DATA = {
    "is_active": True,
    "sections": [
        {
            "title": "Welcome to Cruizo Support",
            "order": 1,
            "contents": [
                {
                    "type": "text",
                    "text": "Welcome to the Cruizo Help Centre. We are here to ensure your self-drive experience is smooth and transparent. Below you will find detailed guides on our policies, refunds, and vehicle usage rules.",
                    "order": 1,
                }
            ],
        },
        {
            "title": "Booking & Documents (Must Read)",
            "order": 2,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "Why do I need to upload documents?",
                        "answer": "To rent a car, you must upload a valid Driving License and Aadhaar Card in your Profile. This is mandatory for insurance and legal compliance.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "My booking was rejected. Why?",
                        "answer": "Bookings are usually rejected if the uploaded documents are blurry, expired, or do not belong to the user. Ensure your photos are clear.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Important Note on Rejection:",
                        "answer": "If the Admin rejects your booking due to invalid documents, your Base Rental Amount is forfeited (not refunded) because the car slot was blocked. Only the Security Deposit is refunded.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Cancellations & Refunds",
            "order": 3,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I cancel my booking?",
                        "answer": "Go to 'My Bookings' and select the active trip to cancel. Refund amounts depend on when you cancel.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Cancellation Policy:",
                        "answer": "1. More than 2 hours before start: You get a 50% refund of the Base Rental + 100% Security Deposit.\n\n2. Less than 2 hours before start: 0% refund on Base Rental. Only Security Deposit is refunded.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "When will I get my refund?",
                        "answer": "Security deposits and applicable refunds are processed within 7 working days after the trip ends.",
                    },
                    "order": 6,
                },
            ],
        },
        {
            "title": "Payments & Charges",
            "order": 4,
            "contents": [
                {
                    "type": "text",
                    "text": "**What constitutes the Total Payable amount?**",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "You pay: (Rental Hours × Hourly Rate) + (Security Deposit). The Security Deposit is 10x the hourly rate.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "**Why was money deducted from my Security Deposit?**",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "Deductions occur for: Late returns (>30 mins), Excess Mileage, Traffic Fines, or Vehicle Damage.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "Vehicle Issues & Roadside Assistance",
            "order": 5,
            "contents": [
                {
                    "type": "text",
                    "text": "**What if the car breaks down?**",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "Call our Emergency Support immediately. Do not attempt to repair the car yourself without authorization.",
                    "order": 2,
                },
                {"type": "text", "text": "**What if I have an accident?**", "order": 3},
                {
                    "type": "text",
                    "text": "Ensure your safety first. Contact the police if necessary, and then contact Cruizo Support. Do not leave the scene until instructed.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "Late Returns & Extensions",
            "order": 6,
            "contents": [
                {
                    "type": "text",
                    "text": "**I am running late. What should I do?**",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "We offer a 30-minute grace period. If you are later than that, you will be charged 1.5x (one and a half times) the hourly rate for the extra time.",
                    "order": 2,
                },
                {"type": "text", "text": "**Can I extend my trip?**", "order": 3},
                {
                    "type": "text",
                    "text": "Extensions are possible only if the car is not booked by another user. You must request this via the app before your trip ends.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "Contact Us",
            "order": 7,
            "contents": [
                {"type": "text", "text": "**Email Support**", "order": 1},
                {
                    "type": "text",
                    "text": "support@cruizo.in (Replies within 24 hours)",
                    "order": 2,
                },
                {"type": "text", "text": "**Emergency Helpline**", "order": 3},
                {
                    "type": "text",
                    "text": "+91-1234567890 (24/7 for On-Trip Issues)",
                    "order": 4,
                },
            ],
        },
    ],
}

PRIVACY_POLICY_DATA = {
    "is_active": True,
    "sections": [
        {
            "title": "1. Introduction",
            "order": 1,
            "contents": [
                {
                    "type": "text",
                    "text": "Welcome to Cruizo. We value the trust you place in us. This Privacy Policy describes how Cruizo Motor Company Pvt. Ltd. ('Cruizo', 'we', 'us', or 'our') collects, uses, shares, and protects your personal information when you use our website and mobile application. By accessing or using our platform, you agree to the terms of this Privacy Policy.",
                    "order": 1,
                }
            ],
        },
        {
            "title": "2. Information We Collect",
            "order": 2,
            "contents": [
                {
                    "type": "text",
                    "text": "To provide our car rental services and ensure the safety of our fleet, we collect several types of data from you:",
                    "order": 1,
                },
                {
                    "type": "table",
                    "table": {
                        "columns": ["Category", "Data Points", "Purpose"],
                        "rows": [
                            [
                                "Identity Documents (Sensitive)",
                                "Aadhaar Card Number & Image, Driving License Number & Image",
                                "Mandatory for identity verification, age proof (18+), and license validity checks before booking approval.",
                            ],
                            [
                                "Personal Information",
                                "Full Name, Email Address, Mobile Number, Residential Address",
                                "Account creation, communication regarding bookings, and sending booking confirmations.",
                            ],
                            [
                                "Payment Information",
                                "Transaction IDs, Refund Bank Details (we do not store CVV or full card numbers)",
                                "Processing rental charges, security deposits, and processing refunds after the trip.",
                            ],
                            [
                                "Location & Device Data",
                                "GPS Location, IP Address, Device Model",
                                "Vehicle tracking during the trip for safety, mileage calculation, and fraud prevention.",
                            ],
                        ],
                    },
                    "order": 2,
                },
            ],
        },
        {
            "title": "3. How We Use Your Information",
            "order": 3,
            "contents": [
                {
                    "type": "text",
                    "text": "We strictly use your data for the following legitimate business purposes:",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "i. Verification: To manually or automatically verify your Driving License and Aadhaar to prevent fraud and ensure you meet our eligibility criteria.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "ii. Service Fulfillment: To process your booking, manage vehicle pickup/drop-off, and calculate rental fees based on duration and mileage.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "iii. Safety & Security: To monitor vehicle location during the rental period to prevent theft and assist in case of breakdown or accidents.",
                    "order": 4,
                },
                {
                    "type": "text",
                    "text": "iv. Legal Compliance: To share details with traffic police or legal authorities in the event of traffic violations, accidents, or criminal activity involving the vehicle.",
                    "order": 5,
                },
            ],
        },
        {
            "title": "4. Data Sharing & Disclosure",
            "order": 4,
            "contents": [
                {
                    "type": "table",
                    "table": {
                        "columns": ["Recipient", "Reason for Sharing"],
                        "rows": [
                            [
                                "Legal & Traffic Authorities",
                                "We may share your details if you commit a traffic violation (challan) or are involved in an accident, as required by law.",
                            ],
                            [
                                "Payment Processors",
                                "To facilitate the blocking of security deposits and processing of rental payments.",
                            ],
                            [
                                "Insurance Providers",
                                "In the event of an accident/damage claim, your details may be shared with our insurance partners.",
                            ],
                        ],
                    },
                    "order": 1,
                }
            ],
        },
        {
            "title": "5. Data Storage & Security",
            "order": 5,
            "contents": [
                {
                    "type": "text",
                    "text": "i. Encryption: All sensitive documents (Aadhaar/License images) are encrypted during transmission and storage.",
                    "order": 1,
                },
                {
                    "type": "text",
                    "text": "ii. Access Control: Only authorized Cruizo personnel have access to your verification documents for approval purposes.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "iii. Retention: We retain your transaction and usage history for a period required by Indian law (typically 3-5 years) for audit and legal purposes. Document images may be archived securely.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "6. Your Rights",
            "order": 6,
            "contents": [
                {"type": "text", "text": "You have the right to:", "order": 1},
                {
                    "type": "text",
                    "text": "- Access and Review: View the personal data and documents you have uploaded to your Profile.",
                    "order": 2,
                },
                {
                    "type": "text",
                    "text": "- Correction: Update your documents if they expire or if your address changes.",
                    "order": 3,
                },
                {
                    "type": "text",
                    "text": "- Account Deletion: Request deletion of your account, provided you have no active bookings, pending fines, or outstanding dues.",
                    "order": 4,
                },
            ],
        },
        {
            "title": "7. Cookies & Tracking Technologies",
            "order": 7,
            "contents": [
                {
                    "type": "text",
                    "text": "We use cookies to improve your experience on our website, remember your preferences, and analyze site traffic. You can choose to disable cookies through your browser settings, but this may affect the functionality of the platform.",
                    "order": 1,
                }
            ],
        },
        {
            "title": "8. Changes to this Policy",
            "order": 8,
            "contents": [
                {
                    "type": "text",
                    "text": "Cruizo reserves the right to update this Privacy Policy at any time. Significant changes will be notified to you via email or a prominent notice on our App/Website.",
                    "order": 1,
                }
            ],
        },
        {
            "title": "9. Contact Us",
            "order": 9,
            "contents": [
                {
                    "type": "text",
                    "text": "If you have questions regarding this Privacy Policy or your personal data, please contact our Grievance Officer:",
                    "order": 1,
                },
                {"type": "text", "text": "Email: privacy@cruizo.in", "order": 2},
                {
                    "type": "text",
                    "text": "Address: Cruizo Car Rental Pvt. Ltd., 123, High Street, Workafella, Teynampet, Chennai - 600018, Tamil Nadu, India",
                    "order": 3,
                },
            ],
        },
    ],
}

FAQ_DATA = {
    "is_active": True,
    "sections": [
        {
            "title": "Eligibility & Getting Started",
            "order": 1,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "What are the basic requirements to rent a car from Cruizo?",
                        "answer": "You must possess a valid original driving license (LMV non-transport) and a valid Aadhaar card. Both documents must be uploaded to your profile for verification.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Is there an age limit for renting a car?",
                        "answer": "Yes, the renter must be at least 18 years old to book a car with Cruizo.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Do I need to carry physical documents?",
                        "answer": "Yes, you must carry your original driving license and Aadhaar card during the trip for verification by traffic authorities if needed.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I book a car with a learner's license?",
                        "answer": "No, a valid permanent driving license is mandatory. Learner's licenses are not accepted.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Is local address proof required?",
                        "answer": "Your Aadhaar card serves as the primary address proof. Ensure the address details on it are clear and legible.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Profile & Documents",
            "order": 2,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "Where do I upload my documents?",
                        "answer": "You must upload your documents in the 'Customer Profile' page. You need to provide the document numbers along with clear images of your Driving License and Aadhaar.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Why was my document rejected?",
                        "answer": "Documents are usually rejected if the image is blurry, the name doesn't match the profile, the document is expired, or if the wrong document type was uploaded.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I book a car before uploading documents?",
                        "answer": "No, you cannot proceed with a booking until your valid Driving License and Aadhaar images are uploaded to your profile.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Are my uploaded documents safe?",
                        "answer": "Yes, your documents are stored securely and are only used for identity and license verification purposes.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I change my documents later?",
                        "answer": "Yes, you can update your documents in your profile. However, this may trigger a re-verification process.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Pricing & Deposits",
            "order": 3,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "How is the Total Payable amount calculated?",
                        "answer": "The total amount consists of the Rental Base Amount (Duration Hours × Car's Hourly Price) plus the Security Deposit (10 × Car's Hourly Price).",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How much is the security deposit?",
                        "answer": "The security deposit is calculated as 10 times the dynamic hourly rental price of the specific car model you are booking.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "When do I get my security deposit back?",
                        "answer": "The security deposit is refundable within 7 days after the trip ends, subject to deductions for damages, late returns, or traffic violations.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Does the price include fuel?",
                        "answer": "Rental charges cover the car usage. Fuel costs are generally borne by the user unless specified otherwise in specific offers.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Are there hidden charges?",
                        "answer": "Transparency is key. Potential extra charges include late return penalties, excess mileage charges, and deductions for damages/fines.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Cancellation & Refunds (Crucial)",
            "order": 4,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "What if I cancel more than 2 hours before the trip?",
                        "answer": "If you cancel more than 2 hours before the start time, 50% of the base rental amount is refunded, and the security deposit is fully refunded.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What if I cancel less than 2 hours before the trip?",
                        "answer": "If you cancel within 2 hours of the start time, 0% of the base rental is refunded. You will only receive a refund of the security deposit.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What happens if the Admin rejects my booking?",
                        "answer": "If the Admin rejects your booking (e.g., due to invalid documents), the base rental amount is NOT refunded because the time slot was blocked for others. Only the security deposit is refunded.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Why is the rental fee not refunded on Admin Rejection?",
                        "answer": "When you book, that car is reserved and others cannot book it. If the booking is rejected due to your invalid documents, that time slot is wasted, hence the rental fee is retained.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How long do refunds take?",
                        "answer": "Refund processing typically takes 5-7 business days to reflect in your original payment source.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Late Returns & Extensions",
            "order": 5,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "Is there a grace period for returning the car?",
                        "answer": "Yes, we allow a grace period of 30 minutes for returns.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What happens if I am late by more than 30 minutes?",
                        "answer": "Late returns exceeding 30 minutes are charged at 1.5x (one and a half times) the hourly rental rate for the delayed duration.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I extend my trip while it is active?",
                        "answer": "Extensions are subject to availability. You must request an extension via the platform before your trip ends. If the car is booked by another user, extension is denied.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What if I don't extend and still return late?",
                        "answer": "Unapproved late returns disrupt the next customer's booking and will incur the strict 1.5x penalty charges.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Will late fees be deducted from my deposit?",
                        "answer": "Yes, any applicable late fees will be deducted directly from your security deposit before the balance is refunded.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Vehicle Usage & Limits",
            "order": 6,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "Is there a mileage limit?",
                        "answer": "Yes, mileage limits apply to all bookings. Please check the specific car details for the exact limit.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What happens if I exceed the mileage limit?",
                        "answer": "Excess usage incurs additional charges per kilometer, which will be deducted from your security deposit.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I choose a specific car color?",
                        "answer": "Car color is subject to availability at the time of pickup and cannot be guaranteed during booking.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Are pets allowed in the car?",
                        "answer": "Pets are generally not allowed to avoid allergies and cleaning issues for future guests. Exceptions may require prior approval.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Is smoking allowed in the car?",
                        "answer": "No, smoking is strictly prohibited. A cleaning fee will be charged if the car smells of smoke upon return.",
                    },
                    "order": 5,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I let my friend drive?",
                        "answer": "No, only the person whose documents were verified and uploaded to the booking profile is authorized to drive the vehicle.",
                    },
                    "order": 6,
                },
            ],
        },
        {
            "title": "Damages, Fines & Liabilities",
            "order": 7,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "Who pays for traffic fines?",
                        "answer": "The renter is 100% responsible for all traffic violations, challans, and fines incurred during the booking period.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What happens in case of an accident?",
                        "answer": "You must inform Cruizo immediately. The renter is liable for damages as per the terms agreed upon. Do not attempt to repair the car yourself.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Who pays for damages to the car?",
                        "answer": "The renter is responsible for damages. The cost of repairs will be deducted from the security deposit, and any excess amount must be paid by the renter.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What if the car gets scratched?",
                        "answer": "Minor scratches or dents caused during your trip are chargeable. We recommend taking photos of the car before starting your trip.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What if the car breaks down?",
                        "answer": "Contact our support immediately. If the breakdown is due to mechanical failure not caused by negligence, we will assist you. Misuse-related breakdowns are chargeable.",
                    },
                    "order": 5,
                },
            ],
        },
        {
            "title": "Account Management",
            "order": 8,
            "contents": [
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I view my booking history?",
                        "answer": "You can view all your past and upcoming trips in the 'My Bookings' section of your profile.",
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Can I delete my account?",
                        "answer": "You can request account deletion via support, provided there are no active bookings or pending dues.",
                    },
                    "order": 2,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "I forgot my password, what should I do?",
                        "answer": "Use the 'Forgot Password' link on the login page to reset your credentials via your registered email or phone.",
                    },
                    "order": 3,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I contact customer support?",
                        "answer": "You can reach us via the 'Contact Us' page on the website or through the helpline number listed on your booking confirmation.",
                    },
                    "order": 4,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "Why is my account blocked?",
                        "answer": "Accounts may be blocked for policy violations, non-payment of dues, or submission of fraudulent documents.",
                    },
                    "order": 5,
                },
            ],
        },
    ],
}

ADMIN_HELPCENTRE_DATA = {
    "is_active": True,
    "sections": [
        {
            "title": "Getting Started",
            "order": 0,
            "icon": "fa-solid fa-rocket",
            "contents": [
                {
                    "type": "text",
                    "text": "Welcome to the <strong>Cruizo Admin Panel</strong>! This comprehensive guide will help you navigate and manage all aspects of your car rental business efficiently. The admin panel provides you with powerful tools to manage inventory, bookings, users, content, and generate insightful reports.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I access the Admin Dashboard?",
                        "answer": 'After logging in with your admin credentials, you will be automatically redirected to the admin dashboard. You can also access it by clicking on "Dashboard" in the sidebar navigation. The dashboard provides an overview of key metrics, recent bookings, and important notifications.',
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What are the main features available in the admin panel?",
                        "answer": '<ul class="list-disc pl-4 space-y-1"><li><strong>Dashboard:</strong> Overview of business metrics and KPIs</li><li><strong>Inventory Management:</strong> Add, edit, and manage vehicles</li><li><strong>Booking Management:</strong> View and manage all bookings</li><li><strong>User Management:</strong> Manage customers and staff accounts</li><li><strong>Content Management:</strong> Update website content, FAQs, and policies</li><li><strong>Reports:</strong> Generate business analytics and reports</li><li><strong>Backup:</strong> System backup and restore options</li></ul>',
                    },
                    "order": 2,
                },
                {
                    "type": "tip",
                    "text": 'Use keyboard shortcuts for faster navigation: Press <kbd class="px-2 py-1 bg-gray-200 rounded text-sm">Ctrl + K</kbd> to open the quick search menu from anywhere in the admin panel.',
                    "order": 3,
                },
            ],
        },
        {
            "title": "Dashboard Overview",
            "order": 1,
            "icon": "fa-solid fa-chart-line",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>Dashboard</strong> is your command center for monitoring business performance. It displays real-time metrics and key performance indicators to help you make informed decisions.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What metrics are displayed on the dashboard?",
                        "answer": 'The dashboard shows: <ul class="list-disc pl-4 space-y-1 mt-2"><li>Total active bookings and their status distribution</li><li>Revenue metrics (daily, weekly, monthly)</li><li>Fleet utilization rates</li><li>Customer growth trends</li><li>Recent booking activity</li><li>Pending actions requiring attention</li></ul>',
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How often is the dashboard data updated?",
                        "answer": "Dashboard data is refreshed in real-time for critical metrics like active bookings and pending requests. Analytics data such as charts and graphs are updated every 5 minutes. You can manually refresh the data by clicking the refresh button in the top-right corner.",
                    },
                    "order": 2,
                },
            ],
        },
        {
            "title": "Inventory Management",
            "order": 2,
            "icon": "fa-solid fa-car",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>Inventory Management</strong> section allows you to add, edit, and manage your entire fleet of vehicles. Keep your inventory up-to-date to ensure accurate availability for customers.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I add a new vehicle to the inventory?",
                        "answer": 'To add a new vehicle:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Navigate to <strong>Inventory</strong> from the sidebar</li><li>Click the <strong>"Add Vehicle"</strong> button</li><li>Fill in vehicle details: make, model, year, registration number</li><li>Upload vehicle images (minimum 3 recommended)</li><li>Set pricing tiers and availability</li><li>Configure additional features and specifications</li><li>Click <strong>"Save"</strong> to add the vehicle</li></ol>',
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I set vehicle pricing?",
                        "answer": 'Vehicle pricing can be configured in the vehicle edit form. You can set:<ul class="list-disc pl-4 space-y-1 mt-2"><li>Hourly rental rate</li><li>Daily rental rate</li><li>Weekly rental rate</li><li>Security deposit amount</li><li>Extra charges for additional services</li></ul>',
                    },
                    "order": 2,
                },
                {
                    "type": "warning",
                    "text": "Always ensure vehicle registration and insurance documents are up-to-date before making a vehicle available for rental.",
                    "order": 3,
                },
            ],
        },
        {
            "title": "Booking Management",
            "order": 3,
            "icon": "fa-solid fa-calendar-check",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>Booking Management</strong> section provides tools to view, approve, modify, and manage all customer bookings. You can track booking status, handle cancellations, and process extensions.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I approve or reject a booking?",
                        "answer": 'To approve or reject a booking:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Navigate to <strong>Bookings</strong> from the sidebar</li><li>Filter by "Pending" status to see new bookings</li><li>Click on the booking to view details</li><li>Review customer documents and booking information</li><li>Click <strong>"Approve"</strong> or <strong>"Reject"</strong> with a reason</li></ol>',
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I handle booking extensions?",
                        "answer": 'When a customer requests an extension:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Check vehicle availability for the extended period</li><li>Calculate additional charges</li><li>Update the booking end date</li><li>Process additional payment if required</li><li>Notify the customer of the approved extension</li></ol>',
                    },
                    "order": 2,
                },
            ],
        },
        {
            "title": "User Management",
            "order": 4,
            "icon": "fa-solid fa-users",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>User Management</strong> section allows you to manage all user accounts including customers, staff, and administrators. You can view user details, manage permissions, and handle account-related issues.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I create a new staff account?",
                        "answer": 'To create a new staff account:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Navigate to <strong>Users</strong> from the sidebar</li><li>Click <strong>"Add User"</strong></li><li>Fill in staff details and contact information</li><li>Assign appropriate role and permissions</li><li>Set initial password or send invite email</li><li>Click <strong>"Create"</strong> to finalize</li></ol>',
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I manage user permissions?",
                        "answer": 'User permissions are managed through roles. You can:<ul class="list-disc pl-4 space-y-1 mt-2"><li>Assign predefined roles (Admin, Staff, Customer)</li><li>Create custom roles with specific permissions</li><li>Modify existing role permissions</li><li>View permission audit logs</li></ul>',
                    },
                    "order": 2,
                },
            ],
        },
        {
            "title": "Content Management",
            "order": 5,
            "icon": "fa-solid fa-file-lines",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>Content Management</strong> section allows you to update website content including FAQs, terms and conditions, privacy policy, and other static pages.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I update FAQs?",
                        "answer": 'To update FAQs:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Navigate to <strong>Content > FAQs</strong></li><li>Click on an existing FAQ to edit or click <strong>"Add New"</strong></li><li>Enter the question and answer</li><li>Set the display order</li><li>Toggle visibility as needed</li><li>Click <strong>"Save"</strong> to publish changes</li></ol>',
                    },
                    "order": 1,
                },
                {
                    "type": "tip",
                    "text": "Use the preview feature to see how content will appear to customers before publishing.",
                    "order": 2,
                },
            ],
        },
        {
            "title": "Reports & Analytics",
            "order": 6,
            "icon": "fa-solid fa-chart-pie",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>Reports</strong> section provides detailed analytics and business intelligence to help you make data-driven decisions.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "What reports are available?",
                        "answer": 'Available reports include:<ul class="list-disc pl-4 space-y-1 mt-2"><li><strong>Revenue Reports:</strong> Daily, weekly, monthly revenue breakdown</li><li><strong>Booking Reports:</strong> Booking trends, cancellation rates</li><li><strong>Fleet Reports:</strong> Vehicle utilization, maintenance schedules</li><li><strong>Customer Reports:</strong> Customer acquisition, retention rates</li><li><strong>Financial Reports:</strong> Payments, refunds, outstanding balances</li></ul>',
                    },
                    "order": 1,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I export reports?",
                        "answer": 'To export a report:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Navigate to the desired report</li><li>Set the date range and filters</li><li>Click the <strong>"Export"</strong> button</li><li>Choose format (PDF, Excel, CSV)</li><li>The file will download automatically</li></ol>',
                    },
                    "order": 2,
                },
            ],
        },
        {
            "title": "System Backup & Recovery",
            "order": 7,
            "icon": "fa-solid fa-database",
            "contents": [
                {
                    "type": "text",
                    "text": "The <strong>Backup</strong> section allows you to create and manage system backups to protect your data.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I create a backup?",
                        "answer": 'To create a manual backup:<ol class="list-decimal pl-4 space-y-1 mt-2"><li>Navigate to <strong>Backup</strong> from the sidebar</li><li>Click <strong>"Create Backup"</strong></li><li>Select backup type (Full or Incremental)</li><li>Add optional description</li><li>Click <strong>"Start Backup"</strong></li></ol>',
                    },
                    "order": 1,
                },
                {
                    "type": "warning",
                    "text": "It is recommended to create a backup before making major system changes or updates.",
                    "order": 2,
                },
            ],
        },
        {
            "title": "Support & Contact",
            "order": 8,
            "icon": "fa-solid fa-headset",
            "contents": [
                {
                    "type": "text",
                    "text": "If you need additional help or encounter issues not covered in this guide, our support team is here to assist you.",
                    "order": 0,
                },
                {
                    "type": "qa",
                    "qa": {
                        "question": "How do I contact support?",
                        "answer": 'You can reach our support team through:<ul class="list-disc pl-4 space-y-1 mt-2"><li><strong>Email:</strong> support@cruizo.com</li><li><strong>Phone:</strong> +91 1234567890</li><li><strong>Live Chat:</strong> Available 9 AM - 6 PM IST</li></ul>',
                    },
                    "order": 1,
                },
                {
                    "type": "tip",
                    "text": "For urgent issues, please call our support hotline for immediate assistance.",
                    "order": 2,
                },
            ],
        },
    ],
}

__all__ = ["TERMS_DATA", "HELPCENTRE_DATA", "PRIVACY_POLICY_DATA", "FAQ_DATA", "ADMIN_HELPCENTRE_DATA"]