SAMPLE_USERS = [
    ("user1", "user1@example.com", "user1@123", True),
    ("user2", "user2@example.com", "user2@123", True),
    ("user3", "user3@example.com", "user3@123", True),
    ("user4", "user4@example.com", "user4@123", True),
    ("user5", "user5@example.com", "user5@123", True),
    ("user6", "user6@example.com", "user6@123", False),
    ("user7", "user7@example.com", "user7@123", False),
]

PERMISSIONS = {
    "ADMIN": [
        ("system", "admin"),
        ("profile", "read:self"),
        ("profile", "update:self"),
        ("permissions", "create"),
        ("permissions", "read"),
        ("permissions", "update"),
        ("permissions", "delete"),
        ("roles", "create"),
        ("roles", "read"),
        ("roles", "update"),
        ("roles", "delete"),
        ("users", "create"),
        ("users", "read"),
        ("users", "update"),
        ("users", "delete"),
        ("cars", "create"),
        ("cars", "read"),
        ("cars", "update"),
        ("cars", "delete"),
        ("reviews", "read"),
        ("lookups", "create"),
        ("lookups", "read"),
        ("lookups", "update"),
        ("lookups", "delete"),
        ("bookings", "create"),
        ("bookings", "read"),
        ("bookings", "update"),
        ("bookings", "read_all"),
        ("bookings", "update_all"),
        ("payments", "create"),
        ("payments", "read"),
        ("payments", "update"),
        ("payments", "read_all"),
        ("payments", "update_all"),
        ("exports", "create"),
        ("notifications", "send"),
        ("queries", "read"),
        ("queries", "respond"),
        ("queries", "delete"),
        ("terms", "create"),
        ("terms", "read"),
        ("terms", "update"),
        ("terms", "delete"),
        ("helpcentre", "create"),
        ("helpcentre", "read"),
        ("helpcentre", "update"),
        ("helpcentre", "delete"),
        ("privacypolicy", "create"),
        ("privacypolicy", "read"),
        ("privacypolicy", "update"),
        ("privacypolicy", "delete"),
        ("faq", "create"),
        ("faq", "read"),
        ("faq", "update"),
        ("faq", "delete"),
        ("homepage", "create"),
        ("homepage", "read"),
        ("homepage", "update"),
        ("homepage", "delete"),
        ("backup", "create"),
        ("backup", "read"),
        ("backup", "delete"),
        ("backup_schedule", "create"),
        ("backup_schedule", "read"),
        ("backup_schedule", "update"),
        ("backup_schedule", "delete"),
        ("recovery", "create"),
        ("recovery", "read"),
        ("backup_log", "delete"),
    ],
    "CUSTOMER": [
        ("chats", "read"),
        ("chats", "write"),
        ("profile", "read:self"),
        ("profile", "update:self"),
        ("cars", "read"),
        ("users", "update"),
        ("bookings", "create"),
        ("bookings", "read"),
        ("bookings", "update"),
        ("payments", "create"),
        ("payments", "read"),
        ("payments", "update"),
        ("reviews", "read"),
        ("reviews", "create"),
        ("bookings-freeze", "read"),
        ("bookings-freeze", "create"),
    ],
    "SYSTEM": [],
}

__all__ = ["SAMPLE_USERS", "PERMISSIONS"]